source 'http://rubygems.org'

gem 'benchmark-ips'
gem 'hashie', path: '../../..'
# Update omniauth to a pessimistic minor once omniauth releases changes in
# https://github.com/omniauth/omniauth/pull/977
gem 'omniauth', git: 'https://github.com/omniauth/omniauth.git', branch:'master'
gem 'rack-test', '~> 0.6.3'
gem 'rake'
gem 'rspec', '~> 3.5.0'
gem 'sinatra'
