source 'http://rubygems.org'

gem 'hashie', path: '../../..'
# Update omniauth to a pessimistic minor once omniauth releases changes in
# https://github.com/omniauth/omniauth/pull/977
gem 'omniauth', git: 'https://github.com/omniauth/omniauth.git', branch: 'master'
gem 'omniauth-oauth2', '~> 1.4.0'
gem 'rails', '~> 5.0.1'
gem 'rspec', '~> 3.5.0'
gem 'rspec-rails'
