name: CI
on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7
    - name: Run integration tests
      run: |
        for dir in spec/integration/*; do
          echo "testing $dir integration"
          BUNDLE_GEMFILE=$dir/Gemfile bundle install --jobs 4 --retry 3
          BUNDLE_GEMFILE=$dir/Gemfile bundle exec rspec $dir
        done

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: '3.2'
    - name: Run RuboCop
      run: bundle exec rake rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '4.0'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        RUBYOPT: "--disable-error_highlight"
        CI: true
      run: bundle exec rake spec
    - name: Report coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
        flag-name: ruby-${{ matrix.ruby }}
        parallel: true

  test-jruby:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
        jruby:
          - jruby
    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.jruby }}
    - name: Install dependencies
      env:
        JRUBY_OPTS: --debug
      run: bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        JRUBY_OPTS: --debug
        CI: true
      run: bundle exec rake spec
    - name: Report coverage to Coveralls
      if: matrix.os == 'ubuntu'
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
        flag-name: ${{ matrix.jruby }}-${{ matrix.os }}
        parallel: true

  coverage-finished:
    needs: [test, test-jruby]
    runs-on: ubuntu-latest
    steps:
    - name: Report coverage build as finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
